{100}{}{Oh my! A very shapely and seductive looking woman.}
{101}{}{Miria.}
{102}{}{You're not sure, but the measurements 36-24-36 come to mind.}
{103}{}{Your wife Miria.}
{104}{}{Your ex-wife, Miria}
{105}{}{She's admiring her wedding ring.}
{106}{}{She's twirling her hair around her fingers.}
{107}{}{She's looking at her manicure.}
{108}{}{She looks like she's daydreaming.}
{109}{}{There's no denying it, she's a beauty.}

{150}{}{Bitch!}
{151}{}{How dare you show your face around here!}

{152}{}{That's just sick!}
{153}{}{I hope you two are happy together.}

# Node 0
{154}{}{Why, hello there, stranger. I'm Miria.}
{155}{}{I am so pleased you came back. Anything I can do... for you?}
{156}{}{What do you do around here?}
{157}{}{What can you tell me about the slaughterhouse?}
{158}{}{Heard any good rumors?}
{159}{}{Hubba! Hubba!}

# Node 2
{160}{}{Sure. It's so boring around here, and I hardly ever have anyone to really talk to.}

# Node 10
{164}{}{Rumor has it that Farrel stole that watch.}
{165}{}{Why would Farrel steal the watch?}
{166}{}{Isn't Farrel Cornelius' best friend?}
{167}{}{Tell me some more rumors.}

# Node 11
{168}{}{Because poor people tend to steal to make ends meet. Farrel definitely falls in the poor
 category, and that would explain the new tools he bought soon after Cornelius' watch disappeared.}
{170}{}{May I ask you a few more questions?}

# Node 12
{171}{}{Yes, they were thick as thieves, those two. Which is why I think Farrel stole the watch. Who
 else but Farrel would have the access and the opportunity to steal Cornelius' watch?}

# Node 13
{174}{}{There's not much to tell. My family runs the slaughterhouse, and people from all around bring their brahmin in for culling. After the animals are processed we treat and cure the meat, and it's sold to traders who then distribute it to merchants in various towns. [She sighs] All very boring, if you ask me.}

# Node 14
{176}{}{Have you come to the right place! This town is so boring, sometimes it seems like there's nothing else to do but gossip. So the other day I'm... [she enthusiastically talks for quite awhile before you're able to get a word in edgewise]}
{177}{}{What else do you want to know?}
{178}{}{What do you know about the Cornelius' missing watch?}
{179}{}{You mentioned something about Rose?}
{180}{}{What's this about a mutated brahmin?}
{181}{}{Tell me about Davin.}
{182}{}{Let's talk about something else.}

# Node 15
{183}{}{Rose, the lady that runs Rose's Bed and Breakfast? Now, you didn't hear it from me, but have you ever wondered why her 'coop' is so well protected? She says it's to protect her chickens from predators, but if you look close it looks like she's trying to keep something in rather than out. Plus, whoever heard of chickens laying twelve pound eggs?}
{184}{}{Tell me more rumors.}

# Node 16
{186}{}{It's really strange, but I hear some ranchers say that every once in a while a brahmin will give birth to a calf with only one head. Talk about weird!}

# Node 17
{189}{}{Davin's a good guy. I'm definitely not going to dish any dirt on my own brother to you, though. Family is really important to me, and I soooo can't wait to have a family of my own one day.}

# Node 18
{192}{}{Who, me? Oh, I do odd jobs here and there. Surely nothing worth talking about. [She flutters her eyes at you and smiles]}
{193}{}{I really would like to know more about you.}
{194}{}{You're right, enough talk. Let's get it on! You know you want it!}

# Node 19
{196}{}{I'm really touched. Nobody ever tries to get to know me better. All they want is sex, sex, sex!
 I get so tired of having wild sex all the time. I'm so glad you're not like the others.}
{197}{}{Forget about it, Miss Ho-bag. And to think I thought you were special for a moment.}
{198}{}{You know, I'm just a normal guy like everyone else. Why, my friends say, "}
{199}{}{ you're just so cool because you're normal just like everyone else." Yep, normal that's me.}
{200}{}{Well, I've never known anyone as fascinating as you are.}

# Node 20
{202}{}{Want what? Just what are you implying?}
{203}{}{I think you know what I'm talking about, girlie. Come here, I've got something for you. [You smile and start to undress.]}
{204}{}{I didn't mean to imply anything. I'm sorry if I upset you.}

# Node 21
{205}{}{How dare you call me a slut! Let me tell you, I am very picky about the people I sleep with.
 Why, I only slept with 3 or 4 people this month! This conversation is over!}

# Node 22
{206}{}{How disappointing. You are just like everyone else, aren't you?}

# Node 23
{208}{}{No. I don't think so. I'm tired of this conversation. Good bye.}

# Node 24
{209}{}{[She blushes] Stop it, you're embarrassing me. Aren't you are just the sweetest thing? Why don't come over here and sit on the bed with me.}
{210}{}{I think this going too far. Can't we just talk a little?}
{211}{}{I thought you'd never ask. I just feel so comfortable around you, I'm not usually like that with most people.}
{212}{}{All right! You know what I want, baby!}
{213}{}{You are a slut, aren't you!}

# Node 25
{214}{}{I can't take this anymore! You're perfect. [She rips off her clothes, your clothes, and starts probing the the back of your throat with her tongue as she runs her hands over your naked body.]}
{215}{}{[You're overwhelmed by the feeling that your life will never be the same again.]}

# Node 26
{216}{}{That better not mean what I think that means.}
{217}{}{Aoooga!}
{218}{}{Urg?}

# Node 27
{219}{}{Yup! That's what I thought. It's funny how Neanderthal and civilized speech all sound the same on some subjects. [You don't even see her slap coming, but you're fairly sure that bright red hand print on your face will go away eventually.]}

# rape script dialog
{250}{}{Help, Daddy! Get him away!}
{251}{}{Get away!}
{260}{}{Help, Daddy! Get her away!}

{270}{}{Help! Get him away!}
{280}{}{Help! Get her away!}

# wedding script dialog
{400}{}{Daddy!}
{401}{}{Uh oh!}
{402}{}{I surely do!}

{410}{}{Uhh...}
{411}{}{Uhhh... Continue, please...}
{412}{}{I sure the hell...}
{413}{}{Um... I... do.}

{420}{}{Uncle Biff!}

{450}{}{Uhhh, I think daddy's the one you should be talking too.}

{470}{}{Uhhh, I think Uncle Biff's the one you should be talking too.}

{500}{}{Great, I guess this means I have to run this dump now.}

{1000}{}{What's up, babe?}
{1001}{}{What is it, sweetheart?}
{1002}{}{What's on your mind, darling?}
{1003}{}{Can we talk about this later? I'm getting a headache.}
{1004}{}{Hey there, sweetie.}
{1005}{}{No, no, no... not that kind of distance! I just need you hang back a little when we're walking around.}
{1006}{}{Relax, honey. I just need a little more space when we're walking around.}
{1007}{}{I'll try harder, baby. It just seems tough to find "us" time out here in this wasteland.}
{1008}{}{My stuff is your stuff, dear.}
{1009}{}{Of course, sweetie. Do we have to stop with *just* my armor?}
{1010}{}{Sometimes Daddy made me help in the slaughterhouse, so I know a little about sharp stuff like knives. And growing up on a farm, I've shot rifle and a pistol before, but I'm not really a very good shot, and they're *so* noisy. And then there's that gunpowder smell, I mean...}
{1020}{}{We need to talk about the distance between us.}
{1100}{}{I'm all healed up and ready to go, honey.}
{1200}{}{I'm all better, except for a few bruises. Nothing to worry too much about.}
{1300}{}{Well, I mostly feel better -- but I'll need some more time to patch things up when we get some time to rest.}
{1400}{}{Baby, I tried to heal myself as much as I could, but I'm still hurt pretty bad. Do something, honey!}
{1500}{}{Baby, no. We're in this thing together, and I wanna come with you.}
{1600}{}{If you think it's a good idea, then sure. I'll put it away, honey.}
{1700}{}{Aww, does somebody wanna cuddle?}
{1800}{}{But sweetheart, then we won't be able to hold hands! [She sighs] Whatever.}
{1900}{}{Yeah. I'll just follow ten steps behind you, "master." What's next, a damn robe and a veil? Oh and by the way, next time you want some sex... have fun playing with yourself, because I'm planning a headache that day.}

{2000}{}{I think I broke a limb, lover. Better take a look.}
{2001}{}{I feel feverish, lover. I think I am radiated.}
{2002}{}{I feel very sick, lover. I think I am poisoned.}

{5000}{}{That's weird... my nails are all rubbery... oh my God, one just fell off!}
{5001}{}{Honey, look at me! Something's wrong wrong with my skin! Help me, baby!}
{5002}{}{I feel sick... Stay back, I think I'm gonna... [She vomits]}
{5003}{}{Ohhh my God. I feel sooo sick.}
{5004}{}{Arggh, I think I broke something! Help me, honey!}
{5005}{}{Nnnnnnnnnnnggggghhh... ithurtsithurtsohgodithurtsithurts...}
{5006}{}{Baby, help me... it hurts so much!}
{5007}{}{Oh my God, I'm gonna bleed to death! Do something, honey!}

{5010}{}{Ahhh... that feels SO good. You're so good to me, honey.}
{5011}{}{Woah, head rush! Thanks though, babe.}
{5012}{}{Are you sure these are safe, dear?}

{5020}{}{I feel kinda numb, babe. But it's a good numb.}
{5021}{}{Woah, that feels kinda nice.}
{5022}{}{So your tribe uses these to get stoned?}
{5023}{}{This one time I saw my grandad and his buddies burn a whole pile of these in the shed... it was so weird, they started a fire and closed all the windows and doors. I freaked out, of course, and then I told mom, and she freaked out, and...}

{5030}{}{Sweet! Partytime!}
{5031}{}{Mmm, that was good, babe.}
{5032}{}{Trying to get me drunk, huh? Yeah, I know all your little tricks, but I love you anyway.}

{5100}{}{Go here, go there, I can't take it anymore!}
{5101}{}{Quit poking me! Well, I mean, not in public anyway.}
{5102}{}{Feelin' frisky, huh?}
{5103}{}{Can't keep your hands off me, eh?}

{5200}{}{[She blows you a kiss]}
{5201}{}{This outfit makes me look fat, doesn't it? I knew it.}
{5202}{}{[She flashes you a flirty smile]}
{5203}{}{What? Is there something stuck on my ass?}
{5204}{}{*BLUSH*  Stop it sweetie, you're embarrassing me.}
{5205}{}{What, do I have a rash or something?}
{5206}{}{You can never give me too much attention, sweetie.}

{5500}{}{When are we gonna settle down, hon? I want babies. I know, but maybe we can adopt some.}
{5501}{}{Oh please, honey.  Your boobs are SO much nicer than my boobs.  Well, let's ask that guy over there and see what he thinks.}
{5502}{}{I think I'm getting my period, hon. Do we have any more pads?}
{5503}{}{I wonder how dad's coping? Actually, I don't care.  I can't believe he called me a rugmuncher in front of the mayor.}
{5504}{}{Will you do my nails later, sweetheart?  You paint those little hearts on so much better than I can.}
{5505}{}{I like the way you did your hair today, babe.  You look fucking hot.}
{5506}{}{Do you have any hand lotion, babe?}
{5507}{}{We need a vacaction. When are you going to take me somewhere romantic?}
{5508}{}{I have to go pee, honey.}
{5509}{}{But do we *always* have to be on the go? I mean we never even had a honeymoon!}
{5510}{}{No, honey. I love YOU more.}
{5511}{}{Why are we always moving around? I mean, can't we just find a nice farm somewhere and play house for a while?}
{5512}{}{I don't *care* what some girl in your tribe did, I'm *not* getting my clit pierced.}
{5513}{}{Can't we just forget all this stuff and go cuddle somewhere?}
{5514}{}{I love the way that outfit brings out the color in your eyes, sweetie}
{5515}{}{Damn it, you were *so* checking out that girl's ass.  I can't believe you sometimes!}
{5516}{}{Baby *I know* your tribal customs and all, but I'm not gonna walk around topless so every lowlife in the wasteland can stare at my tits.}
{5517}{}{I shaved my legs for this?}
{5518}{}{I don't know if you've noticed or not, but I regularly feel this compulsion to stand in doorways.
 It's not annoying you, is it?}
{5519}{}{What was that, dear? Sorry, I was just thinking about how things are back home in Modoc.}
{5520}{}{OWW! DAMN! I just broke a nail.}
{5521}{}{Do you think I look okay in this outfit?}
{5522}{}{When are we gonna settle down, honey?}
{5523}{}{Oh honey, remind me to get some more maxipads next time we find a store.}
{5524}{}{Do you think there's a jewelry store anywhere around here?}
{5525}{}{You look so handsome today, sweetie.}
{5526}{}{Sweetheart, will you rub my neck later? I'm getting stiff.}
{5527}{}{I still can't get over the nerve of that bitch back there. Who did she think she was, checking out my husband's butt like that?}
{5528}{}{Baby, I need some new clothes. This outfit just isn't working for me.}

{5600}{}{Honey, this place is filthy. Can't you ever take me anywhere nice?}
{5601}{}{That's just great. Slavers and jetheads. You sure know how to show a girl good time.}
{5602}{}{And I thought Modoc was the middle of nowhere!}
{5603}{}{A nice hot bath? That sounds soooo good right now.}
{5604}{}{Well, it sure doesn't look very impressive from out here.}
{5605}{}{So wait, they just sit inside those walls while all these poor people suffer out here right under their noses?}
{5606}{}{Wow, I think this is the cleanest place I've ever seen.}
{5607}{}{And I thought *I* was obsessed with cleanliness!}
{5608}{}{Aww, how cute. All their little outfits match, honey.}
{5609}{}{Are they all related? They look like they're all related to me.}
{5610}{}{Can somebody turn up the heat? It's freezing in here.}
{5611}{}{Woah, look how shiny that floor is! I've gotta find out how they do that.}
{5612}{}{Who said you can never go home again?}
{5613}{}{It's just like I remembered. Unfortunately.}
{5614}{}{I want some brahmin-fries, honey. Buy me some brahmin fries? Pleeeaaassee?}
{5615}{}{This place will never change.}
{5616}{}{I think Davin and his friends used to play down here when they were kids. Gross.}
{5617}{}{Like, ewww!}
{5618}{}{Poor Karl. I would've been scared off too.}
{5619}{}{Oh my God! Wait, they're not real... damn, I feel silly.}
{5620}{}{Okay, this place is freaking me out. Can we leave, like now?}
{5621}{}{Honey, can I wait outside?}
{5622}{}{Where are all the girl ghouls? What kind of sexist town is this, anyway?}
{5623}{}{But their parts are, like, falling off! And they smell so bad! Gross!}
{5624}{}{We shouldn't be down here...}
{5625}{}{For some reason I think they'd look better in red and white jumpsuits. What do you think, honey?}
{5626}{}{Somebody should hose down this place.}
{5627}{}{Is *EVERYTHING* busted here?}
{5628}{}{So this is Vault 13? I was expecting it to be... bigger.}
{5629}{}{So wait, baby, why are we here again?}
{5630}{}{These people must be rich! I've never seen so many big buildings!}
{5631}{}{Oh my gawd, those blue suits are *awful*!}
{5632}{}{So you're related to that giant statue guy? Cool!}
{5633}{}{This place is such a drag, honey. Let's go somewhere fun.}
{5634}{}{Talk about a tale of two cities...}
{5635}{}{I think some of these people are up to no good, sweetie. Don't worry, I'll keep my eyes open.}
{5636}{}{This is just... eerie. I mean, all these abandoned tents, just sitting out here in the middle of nowhere...}
{5637}{}{Make sure you search *EVERYWHERE*, okay? I mean God forbid you should miss out on one freaking stimpack...}
{5638}{}{Woah. Look at all these people!}
{5639}{}{You'd better keep a close eye on me, sweetie. I don't like all these big crowds of people.}
{5640}{}{Look at all those whores. I'm not letting you out of my sight, honey.}
{5641}{}{This place is crazy! There's all these, like, businesses and stuff.}
{5642}{}{It's pretty hard to tell around here, but I think this is the bad side of town.}
{5643}{}{If these people would clean this place up, they could have a nice town here.}
{5644}{}{Someone should start a soup kitchen in one of those abandoned buildings.}
{5645}{}{Someone should start a rehab clinic in one of those abandoned buildings.}
{5646}{}{Okay, this place is freaking me out. Let's get outta here.}
{5647}{}{I don't want to stay here one minute longer than necessary. Do you hear me?!}
{5648}{}{Oh, that slime is just too nasty.}
{5649}{}{So they mined gold here? Like for jewelry and stuff?}
{5650}{}{These people have more brahmin than Daddy!}
{5651}{}{They have gold here, baby! Maybe they have a jewelry store!}
{5652}{}{This place feels... on edge. Know what I mean? No? Oh well.}
{5653}{}{Wait... I thought we didn't like mutants? I'm confused, darling.}
{5654}{}{Maybe we could get one of these houses cheap, honey. You know, so we could settle down and start a family.}
{5655}{}{I don't know, I don't think we should be hanging around that mine.}
{5656}{}{Honey, *please* be careful...}
{5657}{}{We should get outta here right now.}
{5658}{}{So this whole giant place floats across the water? Yeah, right.}
{5659}{}{I'm just a redneck in a rock and roll bar...}
{5660}{}{Something's fishy here... hah! Fishy, get it? Hey, you're the one who married me.}
{5661}{}{Oh gross, that guy has fish guts on his clothes...}
{5662}{}{Wow! I love these buildings! Look at the design work!}
{5663}{}{Wait, aren't these the people that blew up the world?}
{5664}{}{Fly? In the air? Yeah, right.}
{5665}{}{I think they're gonna need a bigger runway.}
{5666}{}{Sweet, someone got this map back in the game!}
{5667}{}{I don't know, those seats don't look very comfortable.}
{5668}{}{How come they all have that brain-dead look on their face?}
{5669}{}{We should start a cult, too, sweetie. People would like, give us stuff. And the new recruits could give me pedicures. Just kidding. Except for the pedicure part.}
{5670}{}{I never knew there were this many computers in the whole world...}
{5671}{}{I've never seen so many smart people in all my life.}
{5672}{}{Let's not hang around here, okay?}
{5673}{}{I sure don't want to do time here.}
{5674}{}{Honey... I'm scared.}
{5675}{}{Do we really have to do this?}
{5676}{}{This is crazy! Let's get out of here!}
{5677}{}{Whoever thought this thing up is one twisted SOB.}
{5678}{}{Uhh... honey, what are we doing here?}
{5679}{}{I can feel the sleaze oozing out of the walls around here.}
{5680}{}{You can do it, sweetheart! I believe in you!}
{5681}{}{Can I get some rad-x, baby?}
{5682}{}{Let's not hang around here. I don't want to turn into one of those things.}
{5683}{}{Aww, look at that cute little puppy. Can we keep him?}
{5684}{}{This just doesn't make any sense.}
{5685}{}{So that thing came from the sky? Really?}
{5686}{}{Aww, honey, when are we going to have some kids?}
{5687}{}{Look at all these poor kids. Can we adopt them?}
{5688}{}{Heh, I lost my virginity down here. Don't ask, it's a long story.}
{5689}{}{When I was little, Daddy told me an angel came every night to collect all the coins down here.}
{5690}{}{Oh honey, I'm so sorry...}
{5691}{}{I... I don't know what to say, sweetheart.}
{5692}{}{These trappers are a rough bunch, babe. Keep me close.}
{5693}{}{I think more than a few of these guys need to visit that bath place. They smell baaaddd.}
{5694}{}{I'm so nervous about meeting your family. I wish I had time to get a manicure and curl my hair first.}
{5695}{}{I can see why nobody ever found out about this place.}
{5696}{}{I sure hope they all like me.}
{5697}{}{So, this is where you grew up? I feel like I understand so much more about you now, honey.}
{5698}{}{I think we're the first people to see this place in years.}
{5699}{}{They sure built 'em big before the apocalypse.}

{5700}{}{I hate caves. Let's not go in there, okay?}
{5701}{}{Oh look. Cavetastic! Yay!}
{5702}{}{Hey, another empty cave!}
{5703}{}{Let's skip the cave tour this time, okay babe?}
{5704}{}{It's dark in there, sweetie. Will you hold my hand?}

{5705}{}{Woah! Look at all that water!}
{5706}{}{Mmmm! The air smells so clean here!}
{5707}{}{DID YOU SEE THAT?! Something *HUGE* just jumped out of the water!}
{5708}{}{Who's up for some skinnydipping?}
{5709}{}{Well I'd love to go swimming, if *someone* would buy me a new swimsuit.}

{5710}{}{I hope we find an oasis soon.  We could both use a bath.}
{5711}{}{I'm thirsty.}
{5712}{}{Look! There's house over there! Over there, silly! Are you bli... eh, where'd it go?}
{5713}{}{I got some sand in my panties, honey.}
{5714}{}{Eww, you're all sweaty. Double eww, I'm all sweaty too!}

{5715}{}{My feet hurt, sweetie.  How about giving me a massage?}
{5716}{}{Can we go downhill now? Just for a little while?}
{5717}{}{What is it with you and mountains, anyway?}
{5718}{}{Ooh, this romantic view really puts me in the mood sweetie.}
{5719}{}{Why are we even here? Nobody in their right mind would live out here.}

{5720}{}{I bet this place was so nice once. I can't believe those fools blew it all up.}
{5721}{}{Yeeooww! What are all those shadows? I'm scared!}
{5722}{}{Do you think we could fix up one of those houses, sweetie? You know, and just live in one place for a while?}
{5723}{}{This place makes me sad. I think I'll go cry.}
{5724}{}{Just think of all the families who used to live here. Until they blew themselves up. What were they thinking?}

{5800}{}{This place gives me the willies.}
{5801}{}{And to think a place like this could just be... forgotten.}
{5802}{}{Sometimes I wish we could settle down to a simple life like this.}
{5803}{}{I'd like to go for a swim, but I'm not sure if I should strip down in front of all these savages... er, I mean, strangers. Sorry, honey.}
{5804}{}{Ah, barefoot and fancy-free. I might be able to get into this kind of lifestyle.}
{5805}{}{Does this place make you think about your home, too, sweetie?}
{5806}{}{A vow of chastity? You're kidding, right?}
{5807}{}{So, are we in Fiat Homo or Fiat Lux?}
{5808}{}{This looks like a nice place to rest for a while.}
{5809}{}{Maybe I should wait outside. Daddy always told me we're Lutherans.}

{6000}{}{When are you gonna buy me a new outfit, babe?}
{6001}{}{It feels so good to be out of that sweaty armor for once.}

{6005}{}{I bet Balthas could fix this up into something really nice.}
{6006}{}{Can't you get something better for me to wear than a stinky old brahmin hide?}

{6010}{}{Hey, does this outfit turn you on? It turns me on...}
{6011}{}{Oh yeah. I look pretty hot in this, don't you think?}

{6015}{}{Hmmm, does this mean I'm your knight in shining armor, sweetie?}
{6016}{}{But it's rusty, sweetie! And it needs a good polish! I'm just saying, I don't like it.}

{6020}{}{Do you think this is a flattering color for me, dear?}
{6021}{}{Check out how this outfit hugs my... oh, you already noticed eh?}

{6025}{}{I know you want me to be safe, darling, but it's sooo hot in here!}
{6026}{}{Woah! Time to kick somebody's ass!}

{6030}{}{Mmfjf mflfffmmmphh? Hmmpphhhmmmmph!}
{6031}{}{Yay! I always wanted to be as big as a fridge!}

{6035}{}{Oh, this is niiiicce... And I *love* this color! Thanks, honey!}
{6036}{}{Nice one, hon! It's a little frumpy, but... can anyone say easy access?}

{6040}{}{This thing better be working.}
{6041}{}{How long do I have to wear all this crap?}

{8000}{}{Okay, baby... but don't be long, okay?}
{8001}{}{Oh, suuuure. That's just GREAT... I guess I'll just sit and file my nails then, ok?}
{8002}{}{I guess so, but you better behave while you're gone! I'll know if you don't!}
{8003}{}{All right, darling. Here, have a kiss for good luck. *smooch*}
{8004}{}{All right. I trust you. Just be safe and come back in one piece, okay sweetheart?}

{8005}{}{Oh I missed you so much, sweetie! While you were gone I... [Miria enthusiastically fills you in on the tiniest details of how she spent every... single... minute... during your absence. Twice.]}
{8006}{}{[She sniffs your clothes and checks your collar]. You're damn lucky I can't smell some other woman's perfume on you. If you're done screwing around, can we leave?}
{8007}{}{[She gives you a tight hug]. Hey babe, I missed you.}
{8008}{}{You look beat, honey. Let's go somewhere and I'll give you a nice massage.}
{8009}{}{Oh baby, I was so worried about you, out there facing God knows what dangers... Please, I can't bear to be apart from you any more!}

{8010}{}{Baby... I don't know, you scare me sometimes... Okay, okay! Please don't start yelling at me again!}
{8011}{}{[For the briefest of moments there's a look of fear in her eyes] Yes dear, of course.}

{9000}{}{I'm sorry, baby. *sob* I'll try harder.}
{9001}{}{Stop, baby, please! I'll do whatever you want!}
{9002}{}{*sob* please, please, don't hurt me anymore honey *sob*}
{9003}{}{[bursts into tears]}
{9004}{}{Asshole! I've had it with you!}
{9005}{}{You can't treat me this way!}
{9006}{}{Enough! I don't have to take your bullshit!}

{9100}{}{She's giving you the evil eye.}
{9101}{}{She looks a bit shabby and has a crazed look in her eyes. She seems very angry.}

{9110}{}{You had your chance. Go jump in a vat.}
{9120}{}{Get away from me. It's over.}
{9130}{}{I'm so sorry, honey. I hope you can forgive me someday.}
{9140}{}{I just stopped by to tell you I found somebody new. She's younger than you, better-looking than you, and she's a lot better in the sack too. I'm outta here.}

{9150}{}{I really missed you, too, Miria.}
{9160}{}{I'm hungry. Let's get moving so you can get }
{9161}{}{breakfast started.}
{9162}{}{supper started.}
{9163}{}{dinner started.}
{9164}{}{my midnight snack ready.}
{9170}{}{Don't sass me, woman. Let's go.}
{9180}{}{[Grab her arm] Get your ass over here, woman.}

{9190}{}{Like I'm going ANYWHERE with you after what you did in Modoc. Get away from me.}

{9200}{}{Let's get going, babe.}
{9201}{}{Are you ready to go, Miria?}

{9210}{}{I'm worried about you. Will you try to patch up your wounds?}
{9211}{}{Dammit woman, put a bandaid on your wounds already.}

{9220}{}{Let's take a look at your equipment.}
{9221}{}{What are you doing? Get over and let me look at your gear.}

{9230}{}{I've got to take care of some things, and it's not safe for you to come along. Will you wait for me here, babe?}
{9231}{}{Sit your ass down right here, woman. Wait for me until I get back.}

{9240}{}{[Kiss her]. Ok, that's all I needed right now.}
{9241}{}{I guess that's all we needed to talk about right now.}
{9242}{}{That's all I wanted to talk to you about right now.}

{9250}{}{Put that weapon away, honey.}
{9251}{}{Put away that weapon! Can't you do anything right?}

{9260}{}{Why don't you slip out of that armor you're wearing?}
{9261}{}{Get that armor off, woman.}

{10000}{}{Let's talk about... us.}

{10001}{}{Really? Sure thing, honey. What's on your mind?}
{10002}{}{I've been wanting to talk to you, too. What's on your mind?}
{10003}{}{Of course, sweetheart. What did you want to talk about?}
{10004}{}{I always have time to talk to my sweetie. What's up?}
{10005}{}{Um... sure. What is it you wanted to talk about?}
{10006}{}{Actually, I changed my mind. We'll talk later.}

{10010}{}{How are things? I mean the big picture. Are you doing okay?}
{10011}{}{I don't know. I mean, my life has changed so much since I met you. Sometimes it's hard to understand all that's happened to me.}
{10012}{}{I guess. Life is hard out here in this wasteland, and sometimes I miss my family. But I'm happy we're together, and I don't have any regrets.}
{10013}{}{Sometimes I miss the simple life and being on the farm back in Modoc, but I wouldn't trade being with you and the excitement of adventuring across the wastelands for anything.}
{10014}{}{It seems like it was just yesterday that I was a little girl, playing with my dolly at the farmhouse. I've had a lot adjust to since we got married, but I think I'm doing okay with it. And being with you makes it all a lot easier, honey.}
{10015}{}{When I was growing up, I never imagined I'd have a life like we have. Now that we're out here doing it, though, I have to say I wouldn't trade the way we live for anything.}
{10016}{}{I'm guess I'm good, babe. You inspire me to be something more than I ever thought I could be, and I really like the unexpected way my life is turning out since I met you.}
{10017}{}{Sometimes I feel lonely out here in this wasteland. I mean, you're always busy saving every clueless fool who crosses our path, and I understand you have to be who you are. But once in a while I wish I had some friends of my own to talk to about things, since I hardly ever get a chance to really talk to you.}
{10018}{}{I don't know. I've been thinking a lot lately about my family and friends back in Modoc. I never thought I'd say this but I guess I sort of miss them, even if they do smell like brahmin dung all the time. At least with all those people around, there was always somebody around for me to talk to.}
{10019}{}{I guess maybe I'm a little jealous sometimes, sweetheart. I mean, we run all over the wastelands meeting interesting new people... and they all want to talk to you, or want your help, or want to be around you. I'm proud of you, but sometimes I feel like a wallflower.}
{10020}{}{Sometimes I feel like I don't really fit in. I mean we're always fighting for our lives, exploring spooky old vaults, and even meddling in politics. I'm just a simple farmgirl, and nothing I experienced growing up really prepared me to deal with any of those things.}
{10021}{}{I don't know, honey. Sometimes I just wish you and I could go somewhere and be alone, and just have a normal life. Our only friends are your friends, we're always doing what you want, and going where you want to go. I know it's selfish, but I hope we can just settle down someday and leave all this excitement behind.}
{10022}{}{I'm happy if you're happy, Miria. Let's talk about something else.}
{10023}{}{I know it's hard for you, Miria, but I'm glad you're adjusting well to my crazy life. Let's talk about something else.}
{10024}{}{Good. We'll talk more later, Miria.}
{10025}{}{I'm glad to hear that. We have to get moving now, but we'll talk more later.}
{10026}{}{This is all my fault, and I'll try harder, Miria. Let's talk about something else.}
{10027}{}{I know it's hard sometimes, but you have to believe I'm doing what's best for us both. Let's talk about something else.}
{10028}{}{I'm trying, honey, but all this is new to me too. We'll talk more about this later.}
{10029}{}{I understand. I feel the same things sometimes. We have to go now, but we'll talk more later.}

{10030}{}{I love you, Miria. Sometimes I feel bad that I don't tell you that more often.}
{10031}{}{I just wanted to tell you I love you, that's all. [Kiss her]}
{10032}{}{I love you, honey. You'll always be the only girl for me.}
{10033}{}{[Hold Miria's hand]. Sometimes I wonder if you know how crazy I am about you, honey. I'm so lucky to have a wife like you.}
{10034}{}{Aww, that's sweet. I love you too, honey.}
{10035}{}{[She gets misty-eyed for a moment]. Thank you, sweetie. How do always know just when I need to hear that from you?}
{10036}{}{I'm so lucky to have you. And just for the record, I love YOU more.}
{10037}{}{[She leans in and kisses you] I love you, too.}
{10038}{}{[Miria smiles and softly touches your cheek]}
{10039}{}{Now you've got me all hot and bothered. Wanna go somewhere and fool around?}
{10040}{}{You're the best wife ever. Let's find somewhere quiet, I want to make love to you.}
{10041}{}{Let's talk about something else, Miria.}
{10042}{}{I hate to say this, but we have to go now, Miria.}
{10043}{}{We'll talk more later, Miria. Let's get going.}

{10048}{}{You look really good today, babe. You really are the most beautiful woman in this whole wasteland.}
{10049}{}{Did you do something different with your hair today? You look so beautiful, honey.}
{10050}{}{You look ravishing in that outfit, darling. I didn't think it was possible, but you really do get better looking every day.} 
{10051}{}{You're so pretty, Miria. And every woman we meet is SO jealous of you. Is it ever a hassle, being so beautiful?}
{10052}{}{Thank you, sweetie. You always know just the right thing to say to me.}
{10053}{}{Aww. I try so hard to be sexy for you, I'm glad it's working. [She giggles]}
{10054}{}{That's sweet. I'm glad I can still inspire some passion in you.}
{10055}{}{I love it when you sweet-talk me, babe. Thanks, I needed to hear that.}
{10056}{}{You're so good to me. Thank you, honey.}

{10057}{}{I'm so jealous of your nails, babe. How do you keep you cuticles in such good shape?}
{10058}{}{My hair is always so dull and lifeless in this humidity. How do you keep yours so shiny and vibrant?}
{10059}{}{We're both out here running around the same wasteland, but my skin is like sandpaper while yours is always as soft as silk. What's your secret?}
{10060}{}{My feet are all cracked and dry from running around in sand and toxic goo all day, but yours are always so smooth and healthy-looking. Do you put some kind of lotion or something on them?}
{10061}{}{We can be out here stomping around the desert for days, fighting for our lives in 110 degree heat, but you always smell so good. Is it some kind of herbal perfume you use?}
{10062}{}{I was looking at one of those Cat's Paw magazines and saw that before the Apocalypse many of our female ancestors scraped all the hair from their legs and under their arms. Should we try that? Should we just use a knife, or try some kind of adhesive to pull it off?}
{10063}{}{I'm so stressed, honey. On top of that, we're usually too busy staying alive to get enough sleep or eat a healthy diet. We're both riding the same brahmin out here, but I've got these nasty dark bags under my eyes and you don't. Do you have any ideas how I can get rid of them?}
{10064}{}{Woah, you look great! What plants do you use to prepare that powdered dye you rub on your cheeks to give them that hale, rosy-red glow?}
{10065}{}{Is that... did you put something on your eyelashes to make them look so dark and lush? How did you apply it so evenly, without any clumping?}

{10066}{}{No, really babe. You are SO fine. Let's go somewhere and make out.}
{10067}{}{You look so enchanting, I can barely concentrate. Let's go somewhere quiet... I've got to have you right now, honey.}
{10068}{}{Let's talk about something else, Miria.}
{10069}{}{I could go on about your beauty all day, Miria, but we have to get going now.}

{10070}{}{Are WE doing okay? Are you happy with our marriage?}
{10071}{}{I'm crazy about you, babe. I think everything's great between us.}
{10072}{}{I love you more than ever, honey. I'm so lucky to be your wife.}
{10073}{}{I've never been happier. You're the best, darling.}
{10074}{}{I don't know, I... suppose we're okay. It's just that you're always so busy, sometimes I get jealous and wish we could spend more time together.}
{10075}{}{Well, marriage is a mixed-bag, sweetheart. Sometimes I just feel so lonely, and wish you'd spend more time with me.}
{10076}{}{I... guess so. We're just always so busy and on the move all the time, and the only friends we have are your friends. I'm sorry, it's selfish, but sometimes I wish I could have you to myself for a while.}
{10077}{}{I love you and I'm happy, but I'm worried about you. You... well... you seem use a lot of drugs, honey. Sometimes you're not yourself. You just seem... a little crazy when you're on that stuff.}
{10078}{}{I wish we had more time together. It seems like you're always busy with something else, and then when we do get a break all you want to do is get wasted on drugs. I'm worried about you, dear.}
{10079}{}{Our marriage is everything I ever wanted, but I'm worried about you. I know those slavers are your friends, but... I mean, they're a really rough bunch, and I don't like the way I feel when we're around them. It just seems like a really dangerous way to make a few extra bucks.}
{10080}{}{Well, I dunno. I guess I sometimes wonder how I fit into your life, honey. You seem like you're always too busy to spend time with me, and then... well, I know you're just trying to provide for us, but I'm not really sure how I feel about your business. It's so brutal, buying and selling people... Oh, I'm just going to be quiet now. [She looks like she's about to cry]}
{10081}{}{Of course I'm happy, honey. It's just... I don't understand some of the decisions you make. Are you sure you know what you're doing, getting in with those gangsters?}
{10082}{}{I don't know, baby. It seems like you just don't have much time for me anymore... especially now that you've gotten us mixed up with those gangs.}
{10083}{}{I know you love me, dear, and I think our marriage is strong. It's just... I worry about you. You seem to stir up a lot of trouble wherever we go, and a lot of people really hate us. I feel safe when I'm with you, but sometimes when you're not around I get scared.}
{10084}{}{Please, baby, don't ask me silly questions like that. [She shivers and cringes, as if she expects you to start beating her] I'm trying so hard, baby. Please just don't get upset with me again.}
{10085}{}{I'm so happy to hear that, Miria. Let's talk about something else.}
{10086}{}{There's nothing more important to me than our marriage, Miria. Let's talk about something else.}
{10087}{}{It makes me feel so good to hear you say that, Miria. We'll talk more later.}

{10088}{}{I'll try harder to be there for you, Miria. Let's talk about something else.}
{10089}{}{I understand how you could feel that way. I'd like to think it all over, so let's go and we'll talk more later.}
{10090}{}{Yeah, well, marriage is a two-way street. Let's go, and you can think about that while we walk.}
{10091}{}{You just don't understand all the pressure I'm under, honey. Let's talk about something else.}
{10092}{}{Well, maybe if you took better care of me I could kick this habit. That's enough talk for now, let's go.}

{10093}{}{Don't worry, honey. I know what I'm doing. We'll talk more later.}
{10094}{}{We've talked about this before, Miria. I know what I'm doing with those guys. Let's talk about something else.}
{10095}{}{I don't have time to explain this whole thing to you again, Miria. Let's go.}
{10096}{}{I love you and I'm happy, but I'm worried about you. You spend an awful lot of time playing with those silly Tragic cards, and you're not taking care of things like you should be.}
{10097}{}{I wish we had more time together. It seems like you're always busy with something else, and then when we do get a break all you want to do is play with those stupid Tragic cards. I'm worried about you, dear.}
{10098}{}{It's not just a game, Miria, it's a lifestyle. Anyway, let's talk about something else.}
{10099}{}{Well maybe if you tried harder, I'd pay more attention to you. I don't want to argue with you, so I'm going to go reorganize my card collection now.}

{11000}{}{You spend an hour swapping personal beauty tips with Miria. It's almost as good as sex, and the two of you feel very close afterwards.}
{11001}{}{You spend some time giving your wife oral sex. It's hard to tell whether the look on her face meant she was in agony or in ecstasy. She won't YOU tell which, of course, but you can be sure she's telling everyone ELSE she knows all about it.}
{11002}{}{Miria spends some time giving you oral sex. Although you appreciate that she's trying to do her best, in the end you use your hand to finish yourself off.}
{11003}{}{You spend some time alone with your wife, each of you happily fulfilling your marital obligations to each other.}
{11004}{}{You make passionate love to your wife.}
{11005}{}{Your wife makes passionate love to you.}
{11006}{}{Miria wants to be 'on top' this time, and she works you over thoroughly.}
{11007}{}{You spend some time giving your wife what you hope is pretty good oral sex. Judging by the way she moaned and screamed, she thought it was better than just 'pretty good.'}
{11008}{}{Miria spends some time giving you absolutely amazing oral sex.}
{11009}{}{You spend some time alone with your wife, having sex so sizzling it's probably illegal in some areas.}
{11010}{}{You spend some time alone with your wife engaging in sex that's almost embarrasingly hot for two married people.}
{11011}{}{You and your wife go at it like wild animals, and are both left sweaty and exhausted... but very satisfied.}
{11012}{}{You make love to your wife. It's really good, since the two of you are getting pretty experienced at knowing how to please each other.}

{11020}{}{Was it good for you too, babe?}
{11021}{}{Mmmm. That was great.}
{11022}{}{Mmmm. I needed that.}
{11023}{}{That was pretty good, sweetie.}
{11024}{}{I love being married.}
{11025}{}{You wore me out, honey. I need a nap.}

{11030}{}{I'm sorry, sweetie, but it's that time of the month for me right now. I'm feeling bloated, my boobs are sore, I have a bad headache, and I just don't think I'd be able to get into it right now even if I was feeling fresh. I'm sure you wouldn't want to be with me anyway while I'm like this.}
{11031}{}{It's that time of the month for me, honey, so we'll have to wait until later. I know how you get, though, so let's find somewhere private and I'll take care of you as best I can.}
{11035}{}{I'm not sure what I was thinking, babe. I've got my period right now, too, so I guess we'll both just save up some lust for later. Let's hit the road.}
{11036}{}{Oh yeah, I forgot about that. I guess I can hold off for a few days, so I'll talk to you later.}
{11037}{}{Thanks, honey. Let's go find that privacy...}
{11038}{}{Err, let's wait until we can both enjoy ourselves. Anyway, I'm not really in the mood anymore after hearing about your period, so I'll talk to you later.}

{11050}{}{I love you and I'm happy, but I'm worried about you. You... well... you drink an awful lot, honey. It's starting to affect your judgement, and it seems like you're not taking care of yourself. I'd be happier if you tried to spend more time sober.}
{11051}{}{I wish we had more time together. It seems like you're always busy with something else, and then when we do get a break all you want to do is get drunk. I'm worried about you, dear.}
{11052}{}{I see. You criticize my life, you're not happy... but you sure don't mind spending the money I bring in for us, right? Let's talk about something else before I lose my temper.}
{11053}{}{I can't deal with your bullshit right now, Miria. Let's go, before I decide to smack you.}
{11054}{}{What, I'm not good enough for you now? Let's talk about something else before I lose my temper.}

{11200}{}{We're in this thing together, Miria. What are your hopes for our future?}
{11210}{}{Let's just try to get through all the things that need to be done right now before we worry about the future.}
{11211}{}{I don't know. I'm starting to think maybe I'd like to go back to Modoc someday. I mean, of course, with you. Absolutely. [She might be frowning, but perhaps her expression just means she's got some food stuck between her teeth]}
{11212}{}{I want to settle down. I want a family. But as chaotic as our lives are, how can I hope to make plans with you about those things?}
{11213}{}{I've got my hands full right now just trying to keep your wounds bandaged and your clothes patched up. We'll worry about the future later.}
{11214}{}{Let's just try to get through today rather than worry about tomorrow.}
{11215}{}{I don't know. Why worry about that right now? We're young, we're in love, and nothing else matters to me. Can't we think about all that serious stuff later?}

{11220}{}{I miss Modoc, honey. All my family and friends are there, and I think it would be a fine place for us to set up a home and raise a tribe-full of children. We could get our own farm, and my family could teach you the cattle business so you can support us. Just think how peaceful it would be, dear. You could run the farm, and every fall you could satisfy your taste for adventure by driving the cattle to Redding or Vault City. Of course I'll be waaay too busy with all the babies we're going to have, but once they're older we could still travel from time to time. You know, maybe take a vacation and go somewhere romantic once in a while?}
{11221}{}{Do you ever miss your tribal life? I don't know, the idea of a simple life like that is sort of growing on me. I can see us in a modest teepee, with our babies playing all around. Plus, we wouldn't have to lug around all my outfits and shoes if my whole wardrobe consisted of a loincloth. [She flashes you a flirty smile] You could hunt and fish for our food, and I could start a garden to satisfy my green thumb. Who knows, maybe one of our kids could even grow up to be the next chief of the clan?}
{11222}{}{I never thought I'd say this, but the idea of living in a big town has sort of been growing on me.  We could get a nice big house in New Reno, with plenty of rooms for all the babies we're going to have. I'm sure you could find work doing something you like in a town that big, and I'd keep busy running our household. Just think, you could come home from work, and I'd have dinner waiting, and then when we put the kids to bed we could hire a babysitter and go out for a night on the town whenever we want.}
{11223}{}{I never thought I'd say this, but the idea of living in a big town has sort of been growing on me. We could get a nice big house in NCR, with plenty of rooms for all the babies we're going to have. I'm sure you could find work doing something you like in a town that big, and I could tend to our children and keep our household running smoothly. Just think, you could come home from work, and I'd have dinner waiting, and then when we put the kids to bed we could hire a babysitter and go out for a night on the town whenever we want.}
{11224}{}{What do you think about moving into Vault 13? I mean, it is your ancestral home and all, so you have as good a claim to be there as anybody else... Those big vault doors would make me feel safe, and if we need things it's not too far to run to NCR for all the modern amenities. Plus there's plenty of space in that big vault, and plenty of rooms for all the babies we're going to have to play and grow up in a safe environment.}
{11225}{}{  And since you've made friends with those deathclaws, so I'm sure they'd be happy to have us there.}
{11226}{}{  And now that all those nasty deathclaws are gone, the place is just sitting empty anyway.}
{11227}{}{I've been thinking lately that maybe we could make a home for ourselves in Redding. There's plenty of work there, so you can do anything you want.  If you need to satisfy your sense of adventure you can run with the caravans, or if you want something steady you can get into the mining business. Maybe you could even run for sheriff in the next election!  We'll get a nice big house on the outskirts of town, and of course I'll be busy raising all the babies we're going to have. I think we could really be happy there, sweetheart.}
{11228}{}{I think I'd like to live in Vault City, dear. It's safe there, and they have all the latest conveniences... I mean, there's just no higher quality of life anywhere else in this wasteland. We can settle down to a nice, quiet life inside the city walls, and I'm sure they'll find something more interesting for a person of your ability to do than working in the List Office. With all medical technology our children could grow up healthy, and they'll have a chance to go to the finest schools around. The more I think about it, the more I'm sure Vault City is the place for us.}
{11229}{}{I've been thinking lately... I never thought I'd say this, but after being out here in this wasteland with you I guess I'm sort of starting to like this lifestyle. And with your adventurous spirt, honey, I know it would just be too hard for you to ever really settle down in one place. We could be like gypsies, roaming the wilds, meeting new people and seeing new places all the time. Once all your business is settled on the coast, maybe we could head east and see what's over the mountains?}
{11330}{}{I guess you can take the girl out the country, honey, but you'll never take the country out of this girl. I'd like to see us find a nice patch of ground somewhere and build a homestead we can call our own. You can work the land, and I can raise all the babies we're going to have. I want lots of babies! We can do our part to tame this wasteland and make it a better place, and when we get old and grey all our kids and grandkids will help take care of us.}
{11335}{}{I want you to be happy, Miria, and I'm going to give your plan a lot of thought. Let's talk about something else, though.}
{11336}{}{I want to give your ideas some serious thought, Miria, so we'll talk more later. Let's hit the road.}
{11340}{}{I miss Modoc, babe, and I think it would be a fine place for us to make our home.  We could start our own brahmin farm... all my family and friends are there to help us get started.  Plus, it's a peaceful place where we can raise all the babies we're going to have.  Oh honey, I want babies so much!  We'll think of something... I mean if nothing else, lots of merchants pass through Modoc and I'm sure we can pick a smart, handsome guy from time to time to make you preggers.  That would be perfect, because then we'd probably never have to see him again after he left town. What? Well of course you're going to have all our babies, sweetie!  I mean I already know the cattle business, so I'll be busy with that and running our farm to support us while you keep our household and be our kids' mom. I think I want you to have six babies, three boys and three girls.  Just think how wonderful it will be, babe!}
{11341}{}{I want kids soooo much, honey, but let's face it... we could swim in a Vat all day and neither one of us is ever going to have the equipment to knock the other one up.  Maybe we could move to the Den? We could help run the orhphanage there! I mean, even though we can't have our own we'd be able to be around kids all the time, plus it's not too strenous a journey to Arroyo or Modoc for us to visit our families once in a while.}
{11342}{}{I kind of like the sound of the tribal lifestyle you had when you were younger, babe. Maybe we could settle down in Arroyo? But I'm worried... would they understand our relationship? I'm not sure they'd take a positive view of two women making it on our own, without some macho guy to protect us. I guess you know more about it than I do, though, so if you think we could make it work then I'm all for it. And after all, you are the 'Chosen One.' If anybody hassles us you can just tell them to mind their own business, or else kick their ass or something.}
{11343}{}{I never thought I'd say this being a farm girl and all, but I think maybe we should settle down in a bigger town. Maybe New Reno? We can be a little more anonymous in a place with a lot of people like that, and everyone probably won't be so quick to judge us for our lifestyle. You know, I mean.. us being two women with no man around, and all that. Plus we're going to have LOTS of babies, so in a big town we can probably find a decent guy with good genes to sire them who we won't have to run into every day after he's done his part.  I think we could make that work, honey.}
{11344}{}{I never thought I'd say this being a farm girl and all, but I think maybe we should settle down in a bigger town. Maybe NCR? We can be a little more anonymous in a place with a lot of people like that, and everyone probably won't be so quick to judge us for our lifestyle. You know, I mean.. us being two women with no man around, and all that. Plus we're going to have LOTS of babies, so in a big town we can probably find a decent guy with good genes to sire them who we won't have to run into every day after he's done his part.  I think we could make that work, honey.}
{11345}{}{What do you think about moving into your ancestral home, Vault 13? I have a good feeling about the community springing up around there. Since you made friends with all those deathclaws I'm sure they'd be happy to have us, and the people there seem pretty laid back... they probably won't hassle us at all about, you know, being two girls who are married to each other. Plus if we got bored, NCR is close by so you can take me out for a night on the town sometimes. I'd feel safe there, honey, and I think we could be really happy.}
{11346}{}{What do you think about moving into your ancestral home, Vault 13? I mean, now that all those deathclaws are gone the place is just sitting empty, and you've got as good a claim to it as anyone else. Plus I'd feel safe behind those big vault doors, and if we ever need anything NCR isn't too far away. And with all the ranching around there, I could get into the cattle business to support us. Maybe we could even use some of the space in the vault to start an orphanage! I think that would be great, honey. If we can't have kids of our own, we can still help make this wasteland a better place by providing a warm home to needy children with no parents of their own.}
{11347}{}{I've been thinking lately that maybe we could make a home for ourselves in Redding. I mean, I already know all about the cattle business, so we could start a ranch just outside of town and I could support us while you stay home and raise all the babies we're going to have! I can't wait to have a big family with lots of kids... I'm thinking like seven or eight precious little ones. Well, I mean, I'll be busy with the business, so of course you'll bear all our children. I don't know, maybe I might have one, but I mean... we can't both stay at home nursing babies all day! And with all those strapping young miners drifting in and out of town all the time, it'll be no problem for us to find a guy with decent genes to get you pregnant... like every two years or so... who won't stick around to bother us after he does his part. Don't worry, I've got it all worked out. It'll be wonderful, babe!}
{11348}{}{I want babies, honey, but let's face it... we just don't have what it takes to make that happen on our own. That's why I'm thinking we could move to Vault City. It's safe there, the quality of life inside the walls is the highest in the wasteland, and best of all... we won't need a man to father our children! We can sign up for the pregnancy cycles together and let science do the rest! Wouldn't that be too cool, if we each had a baby at the same time? Even more importantly, our kids will have a peaceful place to grow up and they'll get the best and most modern education available anywhere. All the pieces fit, babe. I think Vault City is the key to our future.}
{11349}{}{I've been thinking lately... I never thought I'd say this, but after being out here in this wasteland with you I guess I'm sort of starting to like this lifestyle. And with your adventurous spirt, honey, I know it would just be too hard for you to ever really settle down in one place. We could be like gypsies, roaming the wilds, meeting new people and seeing new places all the time. Once all your business is settled on the coast, maybe we could head east and see what's over the mountains?}
{11355}{}{Your happiness is more important to me than anything, babe, and I'll do my best to make your dreams come true. Let's talk about something else.}
{11356}{}{Miria, what would I ever do without you? It's a solid plan, and I'm sure that together we can make it happen. We'll work more on your idea later.}
{11357}{}{So, you're saying... you want me barefoot and pregnant for the next ten or fifteen years? Well... as long as you promise you'll still love me when my boobs are sagging down to around my ankles, it sounds like pure heaven to me. Let's talk about something else, though.}
{11358}{}{Hmm. So you'll be out and about all day bringing home the bacon while I'll be scrubbing floors, washing clothes, and changing out a few dozen soiled swaddling-cloths from sunrise on? Then you'll come home from work, I'll have dinner ready, and after I put the kids to bed you'll tell me all about your tough day while I change into a sexy outfit for you? We'll talk more about this later, Miria.}

{11370}{}{Things are pretty crazy right now, but I promise it will all get better soon. Let's talk about something else.}
{11371}{}{I feel the same way most of the time, Miria. Let's talk about something else.}
{11372}{}{I know what you mean sometimes.  Let's talk about something else.}

{11375}{}{Someday we'll look back at these hard times and laugh. We'll talk more later.}
{11376}{}{Sure, things are hectic right now. I'm going to take care of everything, though... you'll see. Let's go, and we'll talk more later.}
{11377}{}{Well, I'm sure if we work together we can get through this thing, Miria. We'll talk more later.}

{11380}{}{I don't need this bullshit from you right now, Miria. Let's talk about something else.}
{11381}{}{I'm trying, and maybe someday you'll appreciate that. Let's talk about something else.}
{11382}{}{Well, it's no picnic from where I'm standing either. Let's talk about something else.}

{11385}{}{You know, honey, sometimes being married to you sounded a lot better in the brochure. Let's go before I lose my patience with you.}
{11386}{}{Well, maybe if you'd help me more instead of whining all the time we could get ahead faster in this wasteland. I'll talk to you later.}
{11387}{}{No matter what I do it's never enough for you, is it? I don't even want to talk to you when you're like this.}

{11388}{}{Your happiness is important to me, Miria. Let's talk about something else.}